[package]
name = "monza-execution-util"
description = "Executor for the AptosVM"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

version = { workspace = true }

[lib]
path = "src/lib.rs"

[dependencies]
aptos-types = { workspace = true }
aptos-sdk = { workspace = true }
m1-da-light-node-util = { workspace = true }
anyhow = { workspace = true }

