[workspace.package]
authors = ["Movement Labs"]
edition = "2021"
repository = "https://github.com/movemntdev/sdk"
license = "Apache-2.0"

[workspace]
resolver = "2"
members = [
    # "protocol-units/data-availability",

    # storage
    # "protocol-units/storage/jelly-move",
    # "protocol-units/storage/move-access-log",

    # "protocol-units/cryptography/tentacles",

    "protocol-units/zkfp/host",
    "protocol-units/zkfp/methods",
    "protocol-units/zkfp/methods/guest",
    "protocol-units/minitime",

    # test-helpers
    # "test-helpers/move-vm-integration-test-helpers",

    # types
    # "types/move-vm-ext"
]

exclude = [
    "shared-sequencer/movement-sequencer"
]

[workspace.dependencies]
# random
rand = "0.8.4"

anyhow = "1.0"
# To try (experimental) std support, add `features = [ "std" ]` to risc0-zkvm
risc0-zkvm = { version = "0.20.1",  features = ["std", "getrandom"] }
risc0-build = { version = "0.20.1"  }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# serialization, deserialization
borsh = { version = "0.10" } # todo: internalize jmt and bump
serde = "1.0"
serde_json = "1.0"


tempfile = "3.2.0"

# runtime
tokio = { version = "1.36.0", features = ["fs", "rt-multi-thread"] }

# storage
rocksdb = { version = "0.22.0", features = [
  "snappy",
  "lz4",
  "zstd",
  "zlib",
  "multi-threaded-cf",
], default-features = false }

# cryptography
jmt = "0.9.0"
trie-db = "0.28.0"
sha2 = "0.10"

# for jmt
digest = "0.10" 
hashbrown = "0.14.3"
itertools = { version = "0.12.1", default-features = false }
mirai-annotations = "1.10.1"
num-derive = "0.4.2"
num-traits = "0.2.14"
parking_lot = { version = "0.12.1" } 
thiserror = { version = "1.0.24" } 
blake3 = { version = "1.4.0", features = ["traits-preview"] } 
hex = { vesion = "0.4.3", features = ["serde"] }
tracing = "0.1"
ics23 = { version = "0.11.0" }


proptest = "1.0"
proptest-derive = "0.4"

# internal
# tentacles = { path = "protocol-units/cryptography/tentacles" }
move-vm-integration-test-helpers = { path = "test-helpers/move-vm-integration-test-helpers" }
move-vm-ext = { path = "types/move-vm-ext" }

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3

[patch.crates-io]
merlin = { git = "https://github.com/aptos-labs/merlin" }
x25519-dalek = { git = "https://github.com/aptos-labs/x25519-dalek", branch = "zeroize_v1" }
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.10.8-risczero.0" }
ed25519-dalek = { git = "https://github.com/risc0/curve25519-dalek", tag = "curve25519-4.1.0-risczero.1" }
zstd-sys = { git = "https://github.com/gyscos/zstd-rs.git", rev = "1779b385b42b08f958b767a37878dfa6a0b4f6a4" }
wait-timeout = { git = "https://github.com/movementlabsxyz/wait-timeout", branch = "risc0" }
