[workspace.package]
authors = ["Movement Labs"]
edition = "2021"
version = "0.1.0"
repository = "https://github.com/movemntdev/sdk"
license = "Apache-2.0"

[workspace]
resolver = "2"
members = [
    "protocol-units/data-availability",
    "protocol-units/eth-settlement/eth-adapter",
    "protocol-units/eth-settlement/eth-publisher",
    "protocol-units/eth-settlement/methods",
    "protocol-units/eth-settlement/contracts",
    "protocol-units/clients/eth",
    "tests/integration/methods",
    "tests/integration",

]

exclude = [
    "protocol-units/zkfp/host",
    "protocol-units/zkfp/methods",
    "protocol-units/zkfp/methods/guest",
    "shared-sequencer/movement-sequencer"
]

[workspace.dependencies]
anyhow = "1.0"
async-trait = { version = "0.1" } 
alloy-primitives = { version = "0.6", default-features = false, features = ["rlp", "serde", "std"] }
alloy-sol-types = { version = "0.6" }
bincode = { version = "1.3" }
tokio = { version = "1", features = ["full"] }
# To try (experimental) std support, add `features = [ "std" ]` to risc0-zkvm
tracing = "0.1.40"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = "1.0"
serde_json = "1.0.68"
log = { version = "0.4" }
tempfile = "3.2.0"
ethers = { version = "2.0" }
hex = "0.4.3"
bytemuck = { version = "1.14" }

# Sovereign Labs dependencies
sov-rollup-interface = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", branch = "nightly", features = ["native"] }
sov-mock-da = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", branch = "nightly", features = ["native"] }
web3 = "0.19.0"

# Move dependencies
move-vm-runtime = { path = "protocol-units/zkfp/vendors/move/language/move-vm/runtime" }
move-vm-test-utils = { path = "protocol-units/zkfp/vendors/move/language/move-vm/test-utils" }
move-binary-format = { path = "protocol-units/zkfp/vendors/move/language/move-binary-format" }
move-vm-types = { path = "protocol-units/zkfp/vendors/move/language/move-vm/types"}
move-core-types = { path = "protocol-units/zkfp/vendors/move/language/move-core/types" }
move-compiler = { path = "protocol-units/zkfp/vendors/move/language/move-compiler" }
move-stdlib = { path = "protocol-units/zkfp/vendors/move/language/move-stdlib" }

# Risc0 dependencies
# NOTE: Using a git rev temporarily to get an unreleased version of risc0-build.
# Once the referenced commit is in a released version of risc0-build, this will go back to using a version.
bonsai-rest-api-mock = { version = "0.6.1", default-features = false }
bonsai-sdk = { version = "0.6.1", default-features = false }
risc0-build = { git = "https://github.com/risc0/risc0", rev = "7f731662", features = ["docker"] }
risc0-build-ethereum = { git = "https://github.com/risc0/risc0-ethereum", branch = "release-0.7" }
risc0-ethereum-relay= { git = "https://github.com/risc0/risc0-ethereum", branch = "release-0.7" }
risc0-ethereum-contracts = { git = "https://github.com/risc0/risc0-ethereum", branch = "release-0.7" }
risc0-zkvm = { version = "0.20.1",  features = ["std"] }
risc0-zkp = { version = "0.20", default-features = false }

eth-relay-test-methods = { path = "./tests/integration/methods" }


# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3
