[workspace]

resolver = "2"

members = ["rollup"]

[workspace.package]
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Movement Labs"]
repository = "www.github.com/movementlabs"
homepage = "www.homepage.com"
publish = false
rust-version = "1.73"

[workspace.dependencies]
auto_impl = "1.2.0"
chrono = "0.4.37"
serde = { version = "1.0.192", features = ["derive", "rc"] }
serde_json = { version = "1.0.81", features = [
    "preserve_order",
    "arbitrary_precision",
] } # Note: arbitrary_precision is required to parse u256 in JSON
anyhow = "1.0.68"
derive_more = { version = "0.99.11", default-features = false }
bytes = { version = "1.2.1", default-features = false }
clap = { version = "4.4.10", features = ["derive"] }
hex = { version = "0.4.3", default-features = false, features = [
    "alloc",
    "serde",
] }
async-trait = "0.1.71"
borsh = { version = "0.10.3", features = ["rc", "bytes"] }
tracing = "0.1.40"
tokio = { version = "1.35.1", features = ["full"] }
tempfile = "3.5"
fail = "0.5.1"
jsonrpsee = { version = "0.20.1", features = ["jsonrpsee-types"] }
proptest = { version = "1.3.1", default-features = false, features = ["alloc"] }
poem-openapi = { version = "=2.0.11", features = ["swagger-ui", "url"] }
schemars = { version = "0.8.16", features = ["derive"] }
thiserror = "1.0.50"
x25519-dalek = "1.0.1"
rand = "0.7.3"
rand_core = "0.5.1"
zstd-sys = "2.0.9"

risc0-build = "0.20"

# aptos dependencies
ethereum-types = "0.14.1"
ethers = "=2.0.10"
ethers-core = { version = "=2.0.10", default-features = false }
ethers-contract = "=2.0.10"
ethers-providers = { version = "=2.0.10", default-features = false }
ethers-signers = { version = "=2.0.10", default-features = false }
ethers-middleware = { version = "=2.0.10", default-features = false }

# Aptos dependencies
# We use a forked version so that we can override dependency versions. This is required
# to be avoid depenedency conflicts with other Sovereign Labs crates.
aptos-node = { git = "https://github.com/movementlabsxyz/aptos-core", rev = "806bbf92a34e84bdbc48f58da3a2e51439107c7c" }
aptos-vm = { git = "https://github.com/movementlabsxyz/aptos-core", rev = "806bbf92a34e84bdbc48f58da3a2e51439107c7c" }
aptos-sdk = { git = "https://github.com/movementlabsxyz/aptos-core", rev = "806bbf92a34e84bdbc48f58da3a2e51439107c7c" }
aptos-consensus-types = { git = "https://github.com/movementlabsxyz/aptos-core", rev = "806bbf92a34e84bdbc48f58da3a2e51439107c7c" }
aptos-crypto = { git = "https://github.com/movementlabsxyz/aptos-core", rev = "806bbf92a34e84bdbc48f58da3a2e51439107c7c" }
aptos-db = { git = "https://github.com/movementlabsxyz/aptos-core.git", rev = "806bbf92a34e84bdbc48f58da3a2e51439107c7c" }
aptos-api-types = { git = "https://github.com/movementlabsxyz/aptos-core", rev = "806bbf92a34e84bdbc48f58da3a2e51439107c7c" }
aptos-types = { git = "https://github.com/movementlabsxyz/aptos-core", rev = "806bbf92a34e84bdbc48f58da3a2e51439107c7c" }
aptos-api = { git = "https://github.com/movementlabsxyz/aptos-core", rev = "806bbf92a34e84bdbc48f58da3a2e51439107c7c" }
aptos-storage-interface = { git = "https://github.com/movementlabsxyz/aptos-core", rev = "806bbf92a34e84bdbc48f58da3a2e51439107c7c" }
aptos-block-executor = { git = "https://github.com/movementlabsxyz/aptos-core.git", rev = "806bbf92a34e84bdbc48f58da3a2e51439107c7c" }
aptos-vm-types = { git = "https://github.com/movementlabsxyz/aptos-core", rev = "806bbf92a34e84bdbc48f58da3a2e51439107c7c" }
aptos-vm-logging = { git = "https://github.com/movementlabsxyz/aptos-core", rev = "806bbf92a34e84bdbc48f58da3a2e51439107c7c" }
aptos-language-e2e-tests = { git = "https://github.com/movementlabsxyz/aptos-core", rev = "806bbf92a34e84bdbc48f58da3a2e51439107c7c" }
aptos-framework = { git = "https://github.com/movementlabsxyz/aptos-core", rev = "806bbf92a34e84bdbc48f58da3a2e51439107c7c" }
aptos-config = { git = "https://github.com/movementlabsxyz/aptos-core", rev = "806bbf92a34e84bdbc48f58da3a2e51439107c7c" }
aptos-vm-genesis = { git = "https://github.com/movementlabsxyz/aptos-core", rev = "806bbf92a34e84bdbc48f58da3a2e51439107c7c" }
aptos-executor = { git = "https://github.com/movementlabsxyz/aptos-core", rev = "806bbf92a34e84bdbc48f58da3a2e51439107c7c" }
aptos-executor-types = { git = "https://github.com/movementlabsxyz/aptos-core", rev = "806bbf92a34e84bdbc48f58da3a2e51439107c7c" }
aptos-executor-test-helpers = { git = "https://github.com/movementlabsxyz/aptos-core", rev = "806bbf92a34e84bdbc48f58da3a2e51439107c7c" }
aptos-bitvec = { git = "https://github.com/movementlabsxyz/aptos-core", rev = "806bbf92a34e84bdbc48f58da3a2e51439107c7c" }
aptos-infallible = { git = "https://github.com/movementlabsxyz/aptos-core", rev = "806bbf92a34e84bdbc48f58da3a2e51439107c7c" }
aptos-temppath = { git = "https://github.com/movementlabsxyz/aptos-core", rev = "806bbf92a34e84bdbc48f58da3a2e51439107c7c" }
aptos-event-notifications = { git = "https://github.com/movementlabsxyz/aptos-core", rev = "806bbf92a34e84bdbc48f58da3a2e51439107c7c" }

move-binary-format = { git = "https://github.com/diem/move" }
move-table-extension = { git = "https://github.com/diem/move" }
move-core-types = { git = "https://github.com/diem/move" }

# https://github.com/paradigmxyz/reth/tree/c0655fed8915490f82d4acf8900a16a10554cbfb
reth-primitives = { git = "https://github.com/paradigmxyz/reth", rev = "c0655fed8915490f82d4acf8900a16a10554cbfb", default-features = false }
reth-interfaces = { git = "https://github.com/paradigmxyz/reth", rev = "c0655fed8915490f82d4acf8900a16a10554cbfb" }
reth-rpc-types = { git = "https://github.com/paradigmxyz/reth", rev = "c0655fed8915490f82d4acf8900a16a10554cbfb" }
reth-rpc-types-compat = { git = "https://github.com/paradigmxyz/reth", rev = "c0655fed8915490f82d4acf8900a16a10554cbfb" }
reth-revm = { git = "https://github.com/paradigmxyz/reth", rev = "c0655fed8915490f82d4acf8900a16a10554cbfb" }

# Matches reth dependency. Using exact revision for matching our tightly coupled usage of both reth and revm crates
revm = { version = "8.0.0", default-features = false, features = ["serde"] }
# Used just to be safe about breaking changes
revm-primitives = { version = "=2.0.0", default-features = false }
secp256k1 = { version = "0.27", default-features = false, features = [
    "global-context",
    "rand-std",
    "recovery",
] }

[workspace.lints.rust]
dead_code = "deny"
unused_imports = "deny"
non_ascii_idents = "deny" # Bad for readability and it can also be a security vulnerability

# In case you need inspiration for new lints to add to the list, this is a good
# reference: <https://github.com/EmbarkStudios/rust-ecosystem/blob/6783ae1573d62f3f5439b8ff9e04bec191ec2eaf/lints.toml>.
[workspace.lints.clippy]
debug_assert_with_mut_call = "deny"
inefficient_to_string = "deny"
map_flatten = "deny"
manual_ok_or = "deny"
doc_link_with_quotes = "deny"
match_same_arms = "deny"
semicolon_if_nothing_returned = "deny"

[patch.crates-io]
merlin = { git = "https://github.com/aptos-labs/merlin" }
x25519-dalek = { git = "https://github.com/aptos-labs/x25519-dalek", branch = "zeroize_v1" }
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.10.8-risczero.0" }
ed25519-dalek = { git = "https://github.com/risc0/curve25519-dalek", tag = "curve25519-4.1.0-risczero.1" }
zstd-sys = { git = "https://github.com/gyscos/zstd-rs.git", rev = "1779b385b42b08f958b767a37878dfa6a0b4f6a4" }
