[workspace.package]
authors = ["Movement Labs"]
version = "0.1.0"
edition = "2021"
repository = "https://github.com/movemntdev/sdk"
license = "Apache-2.0"

[workspace]
resolver = "2"
members = [
    "protocol-units/data-availability",
    "protocol-units/zkfp/eth-zk/publisher",
    "protocol-units/zkfp/eth-zk/methods",
    "protocol-units/zkfp/eth-zk/methods/guest",
]

exclude = [
    "protocol-units/zkfp/move-zk/host",
    "protocol-units/zkfp/move-zk/methods",
    "protocol-units/zkfp/move-zk/methods/guest",
    "shared-sequencer/movement-sequencer",
]

[workspace.dependencies]
anyhow = "1.0"
bincode = { version = "1.3" }
bytemuck = { version = "1.14" }
clap = { version = "4.0", features = ["derive", "env"] }
env_logger = { version = "0.10" }
hex = { version = "0.4" }
log = { version = "0.4" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { version = "1.0", features = ["derive", "std"] }
tempfile = "3.2.0"
tokio = { version = "1.35", features = ["full"] }

# Move dependencies
move-vm-runtime = { path = "protocol-units/zkfp/move-zk/vendors/move/language/move-vm/runtime" }
move-vm-test-utils = { path = "protocol-units/zkfp/move-zk/vendors/move/language/move-vm/test-utils" }
move-binary-format = { path = "protocol-units/zkfp/move-zk/vendors/move/language/move-binary-format" }
move-vm-types = { path = "protocol-units/zkfp/move-zk/vendors/move/language/move-vm/types"}
move-core-types = { path = "protocol-units/zkfp/move-zk/vendors/move/language/move-core/types" }
move-compiler = { path = "protocol-units/zkfp/move-zk/vendors/move/language/move-compiler" }
move-stdlib = { path = "protocol-units/zkfp/move-zk/vendors/move/language/move-stdlib" }

#Eth dependencies
ethers = "2.0.13"
alloy-primitives = { version = "0.6", default-features = false, features = ["rlp", "serde", "std"] }
alloy-sol-types = { version = "0.6" }
foundry-compilers = { git = "https://github.com/foundry-rs/compilers" }

#Risc0 / ZK dependencies
# To try (experimental) std support, add `features = [ "std" ]` to risc0-zkvm
risc0-build = { git = "https://github.com/risc0/risc0", rev = "7f731662", features = ["docker"] }
risc0-build-ethereum = { git = "https://github.com/risc0/risc0-ethereum", branch = "release-0.7" }
risc0-zkvm = { version = "0.20.1",  features = ["std"] }
risc0-zkp = { version = "0.20", default-features = false }
risc0-ethereum-contracts = { git = "https://github.com/risc0/risc0-ethereum", branch = "release-0.7" }
bonsai-sdk = { version = "0.6.1" }

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3
