[package]
name = "mcr-settlement-client"
version = { workspace = true }
edition  = { workspace = true }
license  = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#move to workspace when impl is done.
alloy = { workspace = true }
alloy-primitives = { workspace = true  }
alloy_provider = { workspace = true }
alloy-sol-types = { workspace = true  }
alloy_network = { workspace = true }
alloy_transport = { workspace = true }
alloy_transport_http = { workspace = true }
alloy_contract = { workspace = true }
alloy_signer_wallet = { workspace = true }
alloy_rpc_types = { workspace = true }
alloy_transport_ws = { workspace = true }

thiserror = "1.0.60"

anyhow = { workspace = true }
async-stream = { workspace = true }
async-trait = { workspace = true }
movement-types = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
futures = { workspace = true }
alloy_node_bindings = { git = "https://github.com/alloy-rs/alloy.git", package = "alloy-node-bindings"}

[features]
mock = []
default = ["eth"]
stub = []
eth = []

[lints]
workspace = true

