version: "3"

environment:

processes:

  eth:
    command: |
      ./scripts/mcr/run-anvil-for-mcr
    readiness_probe:
      initial_delay_seconds: 3
      exec:
        command: echo "true"
  
  deploy-mcr:
    command: |
      ./scripts/mcr/deploy-mcr-to-anvil
    depends_on:
      eth:
        condition: process_healthy