version: "3"

environment:

processes:

  mcr-client-tests:
    command: |
      set -e
      RUST_BACKTRACE=1 cargo test -p mcr-settlement-client --features integration-tests test_send_commitment -- --test-threads=1
    depends_on:
      build: 
        condition: process_completed_successfully
      setup:
        condition: process_completed_successfully
    availability:
      # NOTE: `restart: exit_on_failure` is not needed since
      # exit_on_end implies it.
      exit_on_end: true