version: "3"

environment:

processes:

  eth:
    command: |
      exit 1
    readiness_probe:
      exec:
        command: echo "true"

  deploy-mcr:
    command: |
      exit 1
    depends_on:
      eth:
        condition: process_healthy