[package]
name = "monza-full-node"
version = { workspace = true }
edition  = { workspace = true }
license  = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maptos-dof-execution = { workspace = true }
m1-da-light-node-client = { workspace = true }
async-channel = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }
sha2 = { workspace = true }
tonic = { workspace = true }
movement-types = { workspace = true }
monza-config = { workspace = true }
dot-movement = { workspace = true }

tracing-subscriber = { workspace = true, optional = true }

[features]
default = [
    "logging"
]
logging = [
    "tracing-subscriber"
]


[lints]
workspace = true
