[package]
name = "tentacles"
version = "0.9.0"
authors = [
    "Liam Monninger <liam@movementlabs.xyz",
    "Penumbra Labs <team@penumbra.zone>",
    "Diem Association <opensource@diem.com>",
]
description = "Jellyfish Merkle Tree and related utilities."
repository = "https://github.com/penumbra-zone/jmt"
homepage = "https://penumbra.zone"
license = "Apache-2.0"
edition = "2021"

keywords = ["merkle-tree", "authenticated"]
category = ["cryptography", "data-structures"]
publish = true

[features]

[dependencies]
anyhow = { workspace = true }
borsh =  { version = "1.3.1", features = ["derive"] }
digest = { workspace = true }
hashbrown = { workspace = true }
itertools = { workspace = true }
mirai-annotations = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
sha2 = { workspace = true }
blake3 = { workspace = true } 
hex = { workspace = true }
tracing = { workspace = true }
ics23 = { workspace = true }

[dev-dependencies]
hex = { workspace = true }
rand = { workspace = true }
parking_lot = { workspace = true }
serde_json = { workspace = true }
proptest =  { workspace = true }
proptest-derive = { workspace = true }
sha2 = { workspace = true }
