[package]
name = "eth-client"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
ethers = { workspace = true }
hex = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

risc0-ethereum-relay = { workspace = true }