[package]
name = "load-soak-testing"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true
rust-version.workspace = true

<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> ee39c4f3 (first version of the Test runtime. Implements only Load test.)
### define here all scenarios execution binaries 
[[bin]]
name = "demoscenario"
path = "bin/demoscenario.rs"
[[bin]]
name = "basicalicebob"
path = "bin/basicalicebob.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
anyhow = { workspace = true }
aptos-sdk = { workspace = true }
>>>>>>> c85c78db (simplify scenario exec error and start adding basic Alice&Bob test)
async-trait = { workspace = true }
=======
>>>>>>> ff595882 (first version of the scenario executor.)
=======
async-trait = { workspace = true }
>>>>>>> ee39c4f3 (first version of the Test runtime. Implements only Load test.)
itertools = { workspace = true, default-features = true }
maptos-execution-util = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
serde  = { workspace = true, features = ["derive"] }
serde_json  = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }
tracing = { workspace = true }
<<<<<<< HEAD
<<<<<<< HEAD
=======

>>>>>>> ff595882 (first version of the scenario executor.)
=======
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
>>>>>>> c61b30ec (create initial project for testing)
=======
url = { workspace = true }


>>>>>>> c85c78db (simplify scenario exec error and start adding basic Alice&Bob test)

[lints]
workspace = true
