[package]
name = "load-soak-testing"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true
rust-version.workspace = true

### define here all scenarios execution binaries 
[[bin]]
name = "demoscenario"
path = "bin/demoscenario.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { workspace = true }
itertools = { workspace = true, default-features = true }
rayon = { workspace = true }
serde  = { workspace = true, features = ["derive"] }
serde_json  = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }
tracing = { workspace = true }


[lints]
workspace = true
