[package]
name = "suzuka-client"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-channel = { workspace = true }
alloy-sol-types = { workspace = true  }
alloy_provider = { workspace = true }
alloy_signer_wallet = { workspace = true }
alloy_network = { workspace = true }
alloy-primitives = { workspace = true  }
alloy_contract = { workspace = true }
alloy_transport = { workspace = true }
alloy_rpc_types = { workspace = true }

aptos-sdk = { workspace = true }
anyhow = { workspace = true }
once_cell = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
rand = { workspace = true }

[dev-dependencies]
reqwest = { workspace = true }
serde_json = { workspace = true }

maptos-execution-util = { workspace = true }
suzuka-executor = { workspace = true }
mcr-settlement-client = { workspace = true }

dotenv = "0.15.0"

[lints]
workspace = true
