[package]
name = "suzuka-client"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

### define here all scenarios execution binaries 
[[bin]]
name = "demoscenario"
path = "bin/demoscenario.rs"
[[bin]]
name = "basicalicebob"
path = "bin/basicalicebob.rs"
[[bin]]
name = "malicious_test"
path = "bin/malicious/malicious_test.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
aptos-sdk = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true, default-features = true }
maptos-execution-util = { workspace = true }
once_cell = { workspace = true }
tokio = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
serde  = { workspace = true, features = ["derive"] }
serde_json  = { workspace = true }
thiserror = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }
tracing = { workspace = true }
url = { workspace = true }
bcs = "0.1.6"

commander = { workspace = true }
buildtime-helpers = { workspace = true }

[dev-dependencies]
reqwest = { workspace = true }

maptos-execution-util = { workspace = true }
mcr-settlement-client = { workspace = true }
suzuka-config = { workspace = true }
dot-movement = { workspace = true }

[lints]
workspace = true
