[package]
name = "suzuka-client"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "suzuka-client-e2e-simple-interaction"
path = "src/bin/e2e/simple_interaction.rs"

[dependencies]
async-channel = { workspace = true }
alloy-sol-types = { workspace = true  }
alloy-provider = { workspace = true }
alloy-signer-wallet = { workspace = true }
alloy-network = { workspace = true }
alloy-primitives = { workspace = true  }
alloy-contract = { workspace = true }
alloy-transport = { workspace = true }
alloy-rpc-types = { workspace = true }

aptos-sdk = { workspace = true }
aptos-types = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true, default-features = true }
maptos-execution-util = { workspace = true }
mcr-settlement-config = { workspace = true }
once_cell = { workspace = true }
tokio = { workspace = true }
rand = { workspace = true }
commander = { workspace = true }
buildtime-helpers = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
chrono = { workspace = true }
bcs = { workspace = true }
rayon = { workspace = true }
serde_json  = { workspace = true }
thiserror = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }
tracing = { workspace = true }
url = { workspace = true }
reqwest = { workspace = true }
mcr-settlement-client = { workspace = true }
suzuka-config = { workspace = true }
dot-movement = { workspace = true }

[dev-dependencies]
reqwest = { workspace = true }
serde_json = { workspace = true }

maptos-execution-util = { workspace = true }
mcr-settlement-client = { workspace = true }
suzuka-config = { workspace = true }
dot-movement = { workspace = true }

dotenv = "0.15.0"

[lints]
workspace = true
