[package]
name = "mcr-settlement-config"
description = "Configuration of the MCR settlement client"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
serde = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
toml = { workspace = true }

[lints]
workspace = true
