[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true } 
risc0-zkvm = { workspace = true }
tracing-subscriber = { workspace = true }
tempfile = { workspace = true }
serde = { workspace = true } 

methods = { path = "../methods" }

# Move dependencies. 
move-vm-runtime = { workspace = true }
move-vm-test-utils = { workspace = true }
move-binary-format = { workspace = true}
move-vm-types = { workspace = true }
move-core-types = { workspace = true }
move-compiler = { workspace = true }
move-stdlib = { workspace = true }


