services:

  m1-da-light-node-celestia-appd:
    image: ghcr.io/movementlabsxyz/m1-da-light-node-celestia-appd:${REV}
    container_name: m1-da-light-node-celestia-appd
    environment:
      DOT_MOVEMENT_PATH: /.movement
      CELESTIA_RPC_ADDRESS: m1-da-light-node-celestia-appd:26657
    volumes:
      - ${DOT_MOVEMENT_PATH}:/.movement
    depends_on:
      setup:
        condition: service_completed_successfully
    ports:
      - "26657:26657"
      - "9090:9090"
    healthcheck:
      test: [ "CMD-SHELL", "echo 'health check'" ]
      retries: 1
      start_period: 5s

  m1-da-light-node-celestia-bridge:
    image: ghcr.io/movementlabsxyz/m1-da-light-node-celestia-bridge:${REV}
    container_name: m1-da-light-node-celestia-bridge
    environment:
      DOT_MOVEMENT_PATH: /.movement
    volumes:
      - ${DOT_MOVEMENT_PATH}:/.movement
    ports:
      - "26658:26658"
    depends_on:
      setup:
        condition: service_completed_successfully
      m1-da-light-node-celestia-appd:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "echo 'health check'" ]
      retries: 1
      start_period: 3s

  celestia-light-node:
    image: busybox
    container_name: celestia-light-node
    command: sh -c 'echo "Starting Celestia light-node services." && sleep infinity'
    environment:
      - DOT_MOVEMENT_PATH=/.movement
    volumes:
      - ${DOT_MOVEMENT_PATH}:/.movement
    depends_on:
      m1-da-light-node-celestia-appd:
        condition: service_healthy
      m1-da-light-node-celestia-bridge:
        condition: service_healthy
