version: "3"

environment:

processes:

  build:
    command : |
      exit 0

  celestia-light-node:
    command: |
      exit 1

  celestia-light-node-synced:
    command: |
      sleep 10
      cargo run --bin wait-for-celestia-light-node
    depends_on:
      celestia-light-node:
        condition: process_healthy

  m1-da-light-node:
    command: |
      ./target/debug/m1-da-light-node
    depends_on:
      celestia-light-node-synced:
        condition: process_completed
      celestia-light-node:
        condition: process_healthy
    readiness_probe:
      exec:
        command: echo "true"

  monza-full-node:
    command: |
      ./target/debug/monza-full-node
    depends_on:
      m1-da-light-node:
        condition: process_healthy
    readiness_probe:
      initial_delay_seconds: 60
      exec:
        command: |
          echo "true"

  monza-faucet:
    command : |
      ./scripts/monza/faucet
    depends_on:
      monza-full-node:
        condition: process_healthy
    readiness_probe:
      exec:
        command: echo "true"

