version: "3"

environment:

processes:

  build:
    command: |
      exit 0

  setup:
    command: |
      exit 0
    depends_on:
      build:
        condition: process_completed_successfully

  celestia-light-node:
    command: |
      exit 1
    depends_on:
      setup:
        condition: process_completed_successfully

  celestia-light-node-synced:
    command: |
      wait-for-celestia-light-node
    depends_on:
      celestia-light-node:
        condition: process_healthy

  m1-da-light-node:
    command: |
      m1-da-light-node
    depends_on:
      celestia-light-node:
        condition: process_healthy
      celestia-light-node-synced:
        condition: process_completed_successfully
    readiness_probe:
      initial_delay_seconds: 5
      exec:
        command: echo "true"

  monza-full-node:
    command: |
      monza-full-node
    depends_on:
      m1-da-light-node:
        condition: process_healthy
    readiness_probe:
      initial_delay_seconds: 5
      exec:
        command: echo "true"

  monza-faucet:
    command : |
      monza-faucet-service run-simple
    depends_on:
      monza-full-node:
        condition: process_healthy
    readiness_probe:
      initial_delay_seconds: 30
      exec:
        command: echo "true"

