version: "3"

environment:

processes:

  monza-client-tests:
    command: |
      sleep 30
      cargo test -p monza-client -- --test-threads=1
    depends_on:
      monza-full-node:
        condition: process_healthy
      monza-faucet:
        condition: process_healthy
    availability:
      # NOTE: `restart: exit_on_failure` is not needed since
      # exit_on_end implies it.
      exit_on_end: true