[package]
name = "suzuka-full-node"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
suzuka-executor = { workspace = true }
m1-da-light-node-client = { workspace = true }
mcr-settlement-client = { workspace = true, features = ["mock"] }
mcr-settlement-manager = { workspace = true }
async-channel = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
sha2 = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
movement-types = { workspace = true }
maptos-rest = { workspace = true }

tracing-subscriber = { workspace = true, optional = true }

dotenv = "0.15.0"

[features]
default = ["logging"]
logging = ["tracing-subscriber"]


[lints]
workspace = true
