version: "3"

environment:

processes:

  m1-da-light-node-e2e-tests:
    command: |
      set -e
      cargo test -p m1-da-light-node-verifier -- --test-threads=1
      cargo test -p m1-da-light-node-client --features "sequencer" -- --test-threads=1
    depends_on:
      celestia-light-node: 
        condition: process_healthy
      m1-da-light-node: 
        condition: process_healthy
    availability:
      exit_on_end: true