services:
  suzuka-full-node:
    image: mvlbs/movement:2f75b348936c0538a8d0aa766ea475235a32a931
    container_name: suzuka-full-node
    ports:
      - "30370:30730" # m1 da light node rpc
      - "30371:30731" # aptos api
      - "30372:30732" # aptos faucet
    environment:
      - CARGO_PROFILE=release
      - MOVEMENT_PREBUILT=true
    command: ["nix", "--extra-experimental-features", "nix-command flakes", "develop", "--command", "just", "suzuka-full-node", "local", "-t=false"]
    volumes:
      - data-volume:/data

volumes:
  data-volume:

