[package]
name = "data-availbility"
version = "0.1.0"
edition = "2021"
description = "Data Availability modules for Movement SDK"

[[bin]]
name = "rollup"
path = "rollup/src/main.rs"

[[bin]]
name = "stf"
path = "stf/src/main.rs"
