[package]
name = "mpt-move"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true } 
tempfile = { workspace = true }

# serialization, deserialization
borsh = { workspace = true }
serde = { workspace = true } 
serde_json = { workspace = true }

# runtime
tokio = { workspace = true }

# cryptography
jmt = { workspace = true }
sha2 = { workspace = true }

# storage
rocksdb = { workspace = true }

# Move dependencies. 
move-core-types = { workspace = true }