version: "3"

environment:

processes:

  eth:
    command: |
      ./scripts/suzuka/run-anvil-for-suzuka
    readiness_probe:
      initial_delay_seconds: 3
      exec:
        command: echo "true"
  
  deploy-mcr:
    command: |
      . ./scripts/suzuka/deploy-mcr-to-anvil
    depends_on:
      eth:
        condition: process_healthy