version: "3"

environment:

processes:

  suzuka-client-loadtests:
    command: |
      LOADTEST_NB_SCENARIO=2 LOADTEST_NB_SCENARIO_PER_CLIENT=2 cargo run -p load-soak-testing --bin basicalicebob
    depends_on:
      suzuka-full-node:
        condition: process_healthy
      suzuka-faucet:
        condition: process_healthy
    availability:
      exit_on_end: false