version: "3"

environment:

processes:
  suzuka-client-tests:
    command: |
      cargo test -p suzuka-client -- --test-threads=1
    depends_on:
      suzuka-full-node:
        condition: process_healthy
      suzuka-faucet:
        condition: process_healthy
      deploy-mcr:
        condition: process_healthy
    availability:
      exit_on_end: false