version: "3"

environment:

processes:

  setup:
    command: |
      cargo run --bin suzuka-full-node-setup
      cargo run -p mcr-settlement-setup --bin one_validator_ceremonial
    depends_on:
      build:
        condition: process_completed_successfully
    