version: "3"

environment:

processes:

  celestia-node-appd:
    command: |
      ./scripts/celestia/celestia-local-appd
    readiness_probe:
      initial_delay_seconds: 10
      exec:
        command: echo "true"
    liveness_probe:
      initial_delay_seconds: 10
      exec:
        command: echo "true"

  celestia-bridge:
    command: |
      ./scripts/celestia/celestia-local-bridge
    readiness_probe:
      initial_delay_seconds: 10
      exec:
        command: echo "true"
    liveness_probe:
      initial_delay_seconds: 10
      exec:
        command: echo "true"
    depends_on:
       celestia-node-appd:
        condition: process_healthy

  celestia-light-node:
    command: |
      sleep 999999999d
      echo "started"
    readiness_probe:
      initial_delay_seconds: 10
      exec:
        command: |
          echo "true"
    liveness_probe:
      initial_delay_seconds: 10
      exec:
        command: |
          echo "true"
    depends_on:
      celestia-node-appd:
        condition: process_healthy
      celestia-bridge:
        condition: process_healthy