[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
gas_limit = 10000000
gas_reports = ["*"]
solc_version = "0.8.26"

[profile.dependencies]
openzeppelin = { git = "https://github.com/OpenZeppelin/openzeppelin-contracts", tag = "v4.7.0" }