[package]
name = "move-access-log"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true } 
tempfile = { workspace = true }

# serialization, deserialization
borsh = { workspace = true }
serde = { workspace = true } 
serde_json = { workspace = true }

# runtime
tokio = { workspace = true }

# cryptography
jmt = { workspace = true }
sha2 = { workspace = true }

# storage
rocksdb = { workspace = true }

# internal
move-vm-ext = { workspace = true }

# Move dependencies. 
move-core-types = { workspace = true }

# testing
move-vm-runtime = { workspace = true }
move-vm-test-utils = { workspace = true }
move-binary-format = { workspace = true }
move-vm-types = { workspace = true }
move-compiler = { workspace = true }
move-stdlib = { workspace = true }
move-vm-integration-test-helpers = { workspace = true }