[package]
name = "publisher"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
alloy-primitives = { workspace = true }
alloy-sol-types = { workspace = true }
anyhow = { workspace = true }
bincode = { workspace = true }
bonsai-sdk = { workspace = true }
bytemuck = { workspace = true }
clap = { workspace = true }
env_logger = { workspace = true }
ethers = { workspace = true }
hex = { workspace = true }
log = { workspace = true }
methods = { path = "../methods" }
risc0-ethereum-contracts = { workspace = true }
risc0-zkvm = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true, features = ["full"] }