name: Checks

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            arch: x86_64
            runs-on: movement-runner
          - os: macos-13-latest
            arch: arm64
            runs-on: macos-13-xlarge

    runs-on: ${{ matrix.runs-on }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main

    - name: Run MCR tests in nix environment
      run: nix develop --command bash  -c "just mcr-contract-tests"

    - name: Run Cargo Check in nix environment
      run: nix develop --command bash  -c "cargo check"  

    # - name: Prebuild binaries in nix environment
    #   run: nix develop --command bash  -c "./scripts/build/prebuild"  

    - name: Run M1 DA Light Node tests in nix environment
      # adjust the log level while debugging
      run: CELESTIA_LOG_LEVEL=FATAL MOVEMENT_PREBUILT=false nix develop --command bash  -c "just m1-da-light-node test.local -t=false"  

    - name: Print available filesystem space
      run: df -h

    - name: Run suzuka tests in nix environment
      # adjust the log level while debugging
      run: CELESTIA_LOG_LEVEL=FATAL MOVEMENT_PREBUILT=false nix develop --command bash  -c "just suzuka-full-node test.local -t=false"  